version: '3.7'

services:
  main_db:
    image: postgres:latest
    container_name: main_db_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - main_db_data:/var/lib/postgresql/data

  test_db:
    image: postgres:latest
    container_name: test_db_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
    ports:
      - "5434:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - main_db
      - test_db
    environment:
      DB_HOST: main_db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST_TEST: test_db
      DB_PORT_TEST: 5432
      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_USER_TEST: ${DB_USER_TEST}
      DB_PASS_TEST: ${DB_PASS_TEST}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  main_db_data:
  test_db_data:
